notifications:
  slack: zewo:VjyVCCQvTOw9yrbzQysZezD1
os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - eval "$(curl -sL https://raw.githubusercontent.com/Zewo/Zewo/master/Scripts/install-swift.sh)"
script:
  - swift package fetch # clones all dependencies
  - rm -rf Packages/*/Tests # deletes dependency's tests until duplicate Package.tests issue can be resolved in SPM. At that point, remove.
  - swift build -Xlinker -rpath -Xlinker $(pwd)/.build/debug/
  - swift build --configuration release -Xlinker -rpath -Xlinker $(pwd)/.build/release/
  - swift test
